[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "endstone-antigrief"
version = "1.5.15"
description = "BlockData-powered anti-grief logging, exact container NBT snapshots, rollback, and WebUI for Endstone"
readme = "README.md"
license = "MIT"
requires-python = ">=3.10"
authors = [
    { name = "TheN1NJ4LL0", email = "joaldrichsh@gmail.com" }
]
keywords = ["endstone", "plugin", "antigrief", "logging", "behavior", "webui", "admin"]

dependencies = [
    "endstone>=0.11.9,<0.12",
    "requests",
    "fastapi>=0.100.0",
    "uvicorn>=0.20.0",
    "bedrock-protocol-packets-ng>=0.0.9",
]


[project.entry-points.endstone]
antigrief = "endstone_antigrief:AntiGriefPlugin"

[tool.hatch.build.targets.wheel]
packages = ["src/endstone_antigrief"]

[tool.hatch.build.targets.sdist]
include = [
    "/src",
    "/README.md",
]
